In [1]:
import os

import pandas as pd

In [ ]:
colet_path = '/work/cvcs2026/LZMM/COLET/dumped/'

gaze_df = pd.read_csv(os.path.join(colet_path, 'gaze_dataset.csv'), sep=',')
pupil_df = pd.read_csv(os.path.join(colet_path, 'pupil_dataset.csv'), sep=',')
blinks_df = pd.read_csv(os.path.join(colet_path, 'blinks_dataset.csv'), sep=',')
annotation_df = pd.read_csv(os.path.join(colet_path, 'annotation_dataset.csv'), sep=',')    # ground truth

In [20]:
metrics = ['mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', 'mean']

for m in metrics:
    annotation_df[m] = annotation_df.apply(
        lambda row: row[f"{m}_{int(row['task_number'])}"], 
        axis=1
    )

cols_to_drop = [f"{m}_{i}" for m in metrics for i in range(1, 5)]
annotation_df = annotation_df.drop(columns=cols_to_drop)

In [ ]:
print('Gaze:')
print(gaze_df.columns.to_list())
display(gaze_df.head(3))

print('Pupil:')
print(pupil_df.columns.to_list())
display(pupil_df.head(3))

print('Blinks:')
print(blinks_df.columns.to_list())
display(blinks_df.head(3))

print('Annotation:')
print(annotation_df.columns.to_list())
display(annotation_df.head(4))

Annotation:
['VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', 'mean']

,VisualAcuity_logMAR_,Gender,Age,Education,task_number,mental,physical,temporal,performance,effort,frustration,mean
0,-0.04,F,28,18,1,10.0,5.0,15.0,25.0,25.0,10.0,15.0
1,-0.04,F,28,18,2,50.0,30.0,25.0,50.0,15.0,25.0,32.5
2,-0.04,F,28,18,3,100.0,10.0,75.0,80.0,90.0,20.0,62.5
3,-0.04,F,28,18,4,60.0,15.0,45.0,50.0,20.0,25.0,35.8

In [ ]:
gaze_drop = ['Education', 'task_number', 'world_index', 'norm_pos_x', 'norm_pos_y', 'base_data', 'gaze_point_3d_x', 'gaze_point_3d_y', 'gaze_point_3d_z', 'eye_center0_3d_x', 'eye_center0_3d_y', 'eye_center0_3d_z', 'gaze_normal0_x', 'gaze_normal0_y', 'gaze_normal0_z', 'eye_center1_3d_x', 'eye_center1_3d_y', 'eye_center1_3d_z', 'gaze_normal1_x', 'gaze_normal1_y', 'gaze_normal1_z']
gaze_df_reduced = gaze_df.drop(columns=gaze_drop)

pupil_drop = ['Education', 'task_number', 'world_index', 'norm_pos_x', 'norm_pos_y', 'method', 'ellipse_center_x', 'ellipse_center_y', 'ellipse_axis_a', 'ellipse_axis_b', 'ellipse_angle', 'diameter_3d', 'model_confidence', 'model_id', 'sphere_center_x', 'sphere_center_y', 'sphere_center_z', 'sphere_radius', 'circle_3d_center_x', 'circle_3d_center_y', 'circle_3d_center_z', 'circle_3d_normal_x', 'circle_3d_normal_y', 'circle_3d_normal_z', 'circle_3d_radius', 'theta', 'phi', 'projected_sphere_center_x', 'projected_sphere_center_y', 'projected_sphere_axis_a', 'projected_sphere_axis_b', 'projected_sphere_angle']
pupil_df_reduced = pupil_df.drop(columns=pupil_drop)

blinks_drop = ['Education', 'task_number', 'id', 'end_timestamp', 'start_frame_index', 'index', 'end_frame_index', 'filter_response', 'base_data']
blinks_df_reduced = blinks_df.drop(columns=blinks_drop)

display(gaze_df_reduced.head(3))
display(pupil_df_reduced.head(3))
display(blinks_df_reduced.head(3))

   VisualAcuity_logMAR_ Gender  Age  gaze_timestamp  confidence
0                 -0.04      F   28     5410.551715    0.999499
1                 -0.04      F   28     5410.555834    0.999653
2                 -0.04      F   28     5410.559774    0.999648

,VisualAcuity_logMAR_,Gender,Age,pupil_timestamp,eye_id,confidence,diameter
0,-0.04,F,28,5410.553797,1,1.000000,40.757561
1,-0.04,F,28,5410.553797,1,0.999646,40.764095
2,-0.04,F,28,5410.557872,0,0.999661,38.729047

   VisualAcuity_logMAR_ Gender  Age  start_timestamp  duration  confidence
0                 -0.04      F   28      5437.625617  0.236131    0.703872
1                 -0.04      F   28      5444.161561  0.180073    0.553669
2                 -0.04      F   28      4937.633752  0.219501    0.632858